language: rust
rust:
- stable
- beta
- nightly
os:
- linux
- osx
#- windows
cache:
  cargo: true
addons:
  apt:
    packages:
      - libaubio-dev
before_install:
  - |-
    case $TRAVIS_OS_NAME in
      osx)
        brew unlink python@2
        brew update
        brew install aubio
        ;;
    esac
script:
- (cd aubio-sys && cargo test --release)
- (cd aubio-lib && cargo test --release)
- (cd aubio-lib && cargo test --release --features with-fftw3)
- (cd aubio-rs && cargo test --release)
- (cd aubio-rs && cargo test --release --features log)
jobs:
  allow_failures:
  - rust: nightly
  include:
  - stage: publish
    script:
    - (cd aubio-sys && cargo publish || true)
    - (cd aubio-lib && cargo publish || true)
    - sleep 10
    - (cd aubio-rs && cargo publish || true)
    if: (type = push) && (tag =~ /^\d+\.\d+\.\d+/)
