language: rust
rust:
- stable
- beta
- nightly
os:
- linux
- osx
- windows
cache: cargo
script:
- |
  cd aubio-sys
  cargo test --release
  cd -
- |
  cd aubio-lib
  cargo test --release
  cargo test --release --features with-fftw3
  cd -
- |
  cd aubio-rs
  cargo test --release --features log
  cd -
jobs:
  allow_failures:
  - rust: nightly
  include:
  - stage: publish
    script:
    - |
      cd aubio-sys
      cargo publish || true
      cd -
    - |
      cd aubio-lib
      cargo publish || true
      cd -
    - |
      cd aubio-rs
      cargo publish || true
      cd -
    if: (type = push) && (tag =~ /^\d+\.\d+\.\d+/)
