language: rust
rust:
- stable
- beta
- nightly
os:
- linux
- osx
- windows
cache:
  cargo: true
  directories:
  - $HOME/AppData/Local/Temp/chocolatey
  - /C/python3
addons:
  apt:
    packages:
      - libaubio-dev
before_install:
  - |-
    rustup component add rustfmt clippy
    case $TRAVIS_OS_NAME in
      windows)
        choco install -y python3 --params "/InstallDir:C:\python3"
        export PATH=/C/python3:$PATH
        python -V
        ;;
      osx)
        brew unlink python@2
        brew update
        brew install aubio
        ;;
    esac
script:
- if [ "$TRAVIS_RUST_VERSION" != "nightly" ]; then cargo fmt && cargo fmt -- --check && cargo clippy -- -D warnings; fi
- (cd aubio-sys && cargo test --release)
- (cd aubio-lib && cargo test --release)
- (cd aubio-lib && if [ "$TRAVIS_OS_NAME" != "windows" ]; then cargo test --release --features with-fftw3; fi)
- (cd aubio-rs && cargo test --release)
- (cd aubio-rs && cargo test --release --features log)
jobs:
  allow_failures:
  - rust: nightly
  include:
  - stage: publish
    script:
    - (cd aubio-sys && cargo publish || true)
    - (cd aubio-lib && cargo publish || true)
    - sleep 10
    - (cd aubio-rs && cargo publish || true)
    if: (type = push) && (tag =~ /^\d+\.\d+\.\d+/)
